# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html

twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'

fos_ck_editor:
    configs:
        main_config:
            toolbar: "ferramentas"

    toolbars:
        configs:
            ferramentas: ["@clipboard", "@basicstyles", "@paragraph"]

        items:
            clipboard: ["Undo", "Redo"]
            basicstyles: ["Bold", "Italic", "Underline" ,"Strike", "Font", "FontSize", "-", "RemoveFormat"]
            paragraph: ["NumberedList","BulletedList", "Indent", "Outdent"]