vich_uploader:
    db_driver: orm

    mappings:
        avatar_perfil:
            uri_prefix: /imagens/perfil
            upload_destination: '%kernel.project_dir%/public/imagens/perfil'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        imagem_post:
            uri_prefix: /imagens/post
            upload_destination: '%kernel.project_dir%/public/imagens/post'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        imagem_evento:
            uri_prefix: /imagens/evento
            upload_destination: '%kernel.project_dir%/public/imagens/evento'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
